/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "intro",
    },
    {
      type: "category",
      label: "Self Hosting",
      items: [
        {
          type: "doc",
          id: "self-hosting/install-store-heroku",
          label: "Heroku",
        },
        {
          type: "doc",
          id: "self-hosting/install-store-docker-compose",
          label: "Docker Compose",
        },
        {
          type: "doc",
          id: "self-hosting/install-store-kubernetes",
          label: "Kubernetes",
        },
      ],
    },
    {
      type: "doc",
      label: "Troubleshoot",
      id: "trouble-shoot",
    },
  ],
};

module.exports = sidebars;
