name: Main

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    environment: github-pages
    env:
      VITE_POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build